title: Journeyman
description: Personal knowledge base and journey notes
theme: minima

markdown: kramdown

collections:
  notes:
    output: true

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "page"