title: StanPan Collection
description: Digital archive of African artefacts, cultural histories, and ritual objects
theme: minima

markdown: kramdown

collections:
  notes:
    output: true

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "page"